#pragma once

#include "sdp/comm_def.h"

namespace MQ_ID
{
    enum : std::uint16_t
    {
        EN_MQ_FORWARDER_NODE_TYPE = SDP::EN_MIN_USER_TASK_TYPE + 1,
        EN_MQ_SCHEDULER_NODE_TYPE,
        EN_MQ_FORWARDER_ACCEPTOR_TYPE,
        EN_MQ_FORWARDER_SERVICE_CONTAINER_TYPE,
        EN_MQ_FORWARDER_SERVICE_TYPE,
        EN_MQ_SCHEDULER_SERVICE_TYPE,
        EN_MQ_SCHEDULER_AGENT_TYPE,
        EN_MQ_CLIENT_SDK_SCHEDULER_SERVICE_TYPE,
        EN_MQ_CLIENT_SDK_AGENT_SERVICE_CONTAINER_TYPE,
        EN_MQ_CLIENT_SDK_AGENT_SERVICE_TYPE,
        EN_MQ_CLIENT_SDK_TASK_TYPE,
        EN_MQ_ANDROID_SDK_TASK_TYPE,
        EN_MQ_MAX_TYPE
    };

    enum : std::uint16_t
    {
        EN_MQ_FORWARDER_NODE_ID = 1,
        EN_MQ_SCHEDULER_NODE_ID = 1,
        EN_MQ_SCHEDULER_SERVICE_ID = 1,
        EN_MQ_FORWARDER_ACCEPTOR_ID = 1,
        EN_MQ_SCHEDULER_AGENT_ID = 1,
        EN_MQ_CLIENT_SDK_SCHEDULER_SERVICE_ID = 1,
        EN_MQ_CLIENT_SDK_AGENT_SERVICE_ID = 1,
        EN_MQ_CLIENT_SDK_TASK_ID = 1,
        EN_MQ_ANDROID_SDK_TASK_ID = 1
    };

    enum : std::uint32_t
    {
        EN_REGIST_MQ_FORWARDER_SERVICE_MSG = SDP::EN_MIN_USER_MSG + 1,
        EN_REGIST_MQ_CLIENT_REQ_MSG,
        EN_REGIST_MQ_CLIENT_RSP_MSG,
        EN_ADD_FOWRARDER_ADDR_NOTIFY_MSG,
        EN_DEL_FOWRARDER_ADDR_NOTIFY_MSG,
        EN_REGIST_MQ_TOPIC_REQ_MSG,
        EN_REGIST_MQ_TOPIC_RSP_MSG,
        EN_FORWARD_REGIST_MQ_TOPIC_REQ_MSG,
        EN_PUB_MQ_TOPIC_MSG,
        EN_PUB_MQ_ADDR_MSG,
        EN_PUB_MQ_BROADCAST_MSG,
        EN_MCS_EXIT_AGENT_NOTIFY,
        EN_AGENT_READY_MSG,
        EN_AGENT_NOT_READY_MSG,

        EN_MAX_MSG
    };
} // namespace MQ_ID